### ISSUE TITLE
React Adsense with Gatsby

### ISSUE THREAD

**Issue by omrllm** [hustcc/react-adsense#16]
Hi!

I have added the `<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>` before `</div>` in the [layout component](https://github.com/anabcrypto/abcrypto/blob/master/src/components/Layout.js).

And `<ReactAdsense />` to [blog-post](https://github.com/anabcrypto/abcrypto/blob/master/src/templates/blog-post.js) to get ads inside the posts.

Inside the ReactAdsense component I didn't type any slot id because I do not have one. 
I'm still in the approval stage.

Repo: [ABCrypto](https://github.com/anabcrypto/abcrypto "ABCrypto")

**Comment by hustcc** [comment]
you should add the script into your html.

**Comment by omrllm** [comment]
what is my html.. that's the problem.

I see only js files

**Comment by hustcc** [comment]
Maybe generate by bundle package tool.

**Comment by hustcc** [comment]
you should know how gatsby generate .html template, and add the script tag into the template.

i have not use gatsby.

**Comment by omrllm** [comment]
Alright I didn't add {``}, that was the error. 
Problem solved, thank you anyway!
