### ISSUE TITLE
the server responded with a status of 400 () ads:1

### ISSUE THREAD

**Issue by chonlatee-s** [hustcc/react-adsense#24]
I have this problem. 
I put <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>  in index.html file.
and make page and add this adsense like this                  
<AdSense.Google
   client='pub-1234567890'
   slot='45678912'
   style={{ display: 'block' }}
   layout='in-article'
   format='fluid'
/>
then the server responded  => Failed to load resource: the server responded with a status of 400 () ads:1
Anyone can help me? Thanks.

**Comment by sbamniya** [comment]
@chonlatee-s How did you fixed that?
