### ISSUE TITLE
How to refresh an adsense unit when route changes ?

### ISSUE THREAD

**Issue by jtexier** [hustcc/react-adsense#6]
Hi, 
I use your package to display adsense units on my react app. 
This works very well the first time the page load but I don't find the way to force units to be refreshed when route changes.
 
Using componentDidMount is ok to load the `(adsbygoogle = window.adsbygoogle || []).push({}) ` part of adsense snippet. But as componentDidMount is only called once, units are never refreshed unless the whole page is reloaded by a cmd(or CTRL)-R. 

I guess componentDidUpdate should be used here, but calling another `(adsbygoogle = window.adsbygoogle || []).push({}) `  leads to Adsense error : 

``` adsbygoogle.push() error: All ins elements in the … with class=adsbygoogle already have ads in them...```  

Any idea how to handle that ?

**Comment by hustcc** [comment]
Maybe we should remove the dom element of adsense, and then, call `(adsbygoogle = window.adsbygoogle || []).push({})`.

**Comment by jtexier** [comment]
Hi, the solution I found was putting an unique key depending on page url to each ad component, that way ads are destroyed and recreated on every page changes.

**Comment by hustcc** [comment]
excellent!

**Comment by cllgeek** [comment]
@jtexier hi,the solution you found,can you give a example,thanks.

**Comment by pratik-aileensoul** [comment]
@jtexier can you give me an example.
Thanks in Advance.

**Comment by jtexier** [comment]
Hi @Pocamus51270, @cllgeek , @pratik-aileensoul  sorry for the late answer during this holyday time. 

The problem is that components have to be removed from the DOM each time the url changes on the browser.  

The solution is to give an unique key to each ads component, something linked to the url (could be a slug) and the format of the unit or an index if you display many units on a list

Example with a post page : 

http://example.com/post/<slug>
 
<AdSense.Google
  key={'300x250-'+post.slug}
  client='ca-pub-7292810486004926'
  slot='7806394673'
/>

Hope it helps.

**Comment by KamleshArya** [comment]
The issue still persists for, adding key does not solve the problem. the library doesn't seem to support any key-related params. @hustcc Can you confirm?

**Comment by janlukasschroeder** [comment]
Alternative solution: 

```js
<AdSense.Google
              key={Math.random()}
              client="ca-pub-8xxxxx"
              slot="7xxxxxxx"
              style={{ display: 'block' }}
              format="rectangle"
              responsive="true"
   />
```
