### ISSUE TITLE
关于props slot

### ISSUE THREAD

**Issue by cllgeek** [hustcc/react-adsense#7]
slot是什么属性啊，写死的吗？

**Comment by hustcc** [comment]
slot 就是广告 id，你在谷歌广告里面创建广告的时候就有了！

**Comment by cllgeek** [comment]
好的，知道了，但是我还有一个疑问，
![1](https://user-images.githubusercontent.com/15187909/43352796-ad0933ca-925b-11e8-8bc9-99ce5c8b5a66.png),这种自动广告怎么处理呢？  谢谢指点

**Comment by hustcc** [comment]
这个不知道啊，你随便点点看看吧😄
